# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2013, 2014, 2015 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

notifications:
  email: false

services:
  - mysql
  - redis
  - mongodb

language: python

# env:
#   - REQUIREMENTS=lowest
#   - REQUIREMENTS=release
#   - REQUIREMENTS=devel

python:
# FIXME: the build times out on Python 2.6 (inveniosoftware/invenio#1789)
#  - "2.6"
  - "2.7"

before_install:
  - "sudo add-apt-repository -y ppa:chris-lea/node.js"
  - "sudo apt-get update"
  #   - "python requirements.py > .travis-lowest-requirements.txt"
  # - "touch .travis-release-requirements.txt"

install:
  - "sudo apt-get -qy install poppler-utils git subversion nodejs --fix-missing"
  - "travis_retry pip install unittest2"
  - "travis_retry pip install --quiet -e git+https://github.com/inveniosoftware/invenio#egg=invenio"
  - "travis_retry pip install --quiet -e .[docs]"
  # - "python setup.py compile_catalog"
  - "inveniomanage config create secret-key"
  - "inveniomanage config set CFG_EMAIL_BACKEND flask_email.backends.console.Mail"
  - "inveniomanage config set CFG_BIBSCHED_PROCESS_USER `whoami`"
  - "inveniomanage config set PACKAGES \"['invenio.base', 'invenio.modules.accounts', 'invenio.modules.records', 'invenio_tags']\""
  - "inveniomanage config set CFG_TMPDIR /tmp"
  - "inveniomanage config set CLEANCSS_BIN false"  # deactivate all the things
  - "inveniomanage config set LESS_BIN false"      # false is /usr/bin/false
  - "inveniomanage config set REQUIREJS_BIN false"
  - "inveniomanage config set UGLIFYJS_BIN false"
  - "inveniomanage config set ASSETS_AUTO_BUILD False"

before_script:
  - "inveniomanage database init --yes-i-know"
  - "inveniomanage database create --quiet"

script:
  - "sphinx-build -qnNW docs docs/_build/html"
  - "python setup.py test"

after_success:
  - coveralls
